### PR TITLE
Allow to use HexaPDF::Reference object for PDF rectangle structure

### PR DESCRIPTION
**Pull request by senzpo**
Prevent errors when points are an object of HexaPDF::Reference

### CODE REVIEW

**Comment by gettalong** [comment]
The `HexaPDF::Rectangle` class is derived from the `HexaPDF::PDFArray` class which handles automatic resolution of PDF references. So inside the `#all?` method `v` will never be a reference.

What is the reason for this pull request? Did you come across a bug?

**Comment by senzpo** [comment]
Yes, I had a bug with the validate method for HexaPDF::Document. Unfortunately, I can't provide exactly the file, because of NDA reason, but the structure looks like 
`[#<HexaPDF::Reference [325, 0]>, #<HexaPDF::Reference [326, 0]>, #<HexaPDF::Reference [327, 0]>, #<HexaPDF::Reference [328, 0]>]`
So it provokes  
> "A PDF rectangle structure must contain an array of four numbers"

**Comment by gettalong** [comment]
That's weird because there is even a test case for this - see https://github.com/gettalong/hexapdf/blob/master/test/hexapdf/test_pdf_array.rb#L29 and https://github.com/gettalong/hexapdf/blob/master/test/hexapdf/test_pdf_array.rb#L160.

* Are you using the latest version of HexaPDF?
* If you can't provide the PDF in question, can you provide the output of `hexapdf inspect FILE.PDF r`? There shouldn't be any confidential information in that output.

**Comment by senzpo** [comment]
Thank's a lot! I just updated version 0.13.0 (was 0.10.0) It works now.

**Pull request closed without merging**
