### PR TITLE
Issue 265: Fix typo in CLI fonts command

### PR DESCRIPTION
**Pull request by robertp**
See https://github.com/gettalong/hexapdf/issues/265

### CODE REVIEW

**Comment by gettalong** [comment]
Thanks for the pull request! Could you please sign the [CLA](https://hexapdf.gettalong.org/contributing.html)? Thanks!

**Comment by robertp** [comment]
> Thanks for the pull request! Could you please sign the [CLA](https://hexapdf.gettalong.org/contributing.html)? Thanks!

Sent

**Comment by gettalong** [comment]
Thanks! I will apply the fix later once I pushed my local changes.

**Comment by gettalong** [comment]
This is now in the devel branch - see https://github.com/gettalong/hexapdf/commit/31a9005246f09f6424c3068e094bb9bea0e09707

**Pull request closed without merging**
